Fix plugin structure

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -2,6 +2,17 @@
 
 set -euo pipefail
 
+# Check required environment variables
+if [ -z "${ASDF_DOWNLOAD_PATH:-}" ]; then
+  echo "Missing ASDF_DOWNLOAD_PATH environment variable" >&2
+  exit 1
+fi
+
+if [ -z "${ASDF_INSTALL_VERSION:-}" ]; then
+  echo "Missing ASDF_INSTALL_VERSION environment variable" >&2
+  exit 1
+fi
+
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
@@ -13,7 +24,7 @@ mkdir -p "$ASDF_DOWNLOAD_PATH"
 release_file="$ASDF_DOWNLOAD_PATH/docker.tgz"
 
 # Download tar.gz file to the download directory
-download_release "$ASDF_DOWNLOAD_VERSION" "$release_file"
+download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 #  Extract contents of tar.gz file into the download directory
 tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" docker/docker || fail "Could not extract $release_file"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,6 +2,22 @@
 
 set -euo pipefail
 
+# Check required environment variables
+if [ -z "${ASDF_INSTALL_TYPE:-}" ]; then
+  echo "Missing ASDF_INSTALL_TYPE environment variable" >&2
+  exit 1
+fi
+
+if [ -z "${ASDF_INSTALL_VERSION:-}" ]; then
+  echo "Missing ASDF_INSTALL_VERSION environment variable" >&2
+  exit 1
+fi
+
+if [ -z "${ASDF_INSTALL_PATH:-}" ]; then
+  echo "Missing ASDF_INSTALL_PATH environment variable" >&2
+  exit 1
+fi
+
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
